// Generated by CoffeeScript 1.7.1
(function() {
  var restore_options, save_options;

  save_options = function() {
    var autoInspectOpen, autoInspectReload;
    autoInspectOpen = document.getElementById("autoInspectOpen").checked;
    autoInspectReload = document.getElementById("autoInspectReload").checked;
    return chrome.storage.sync.set({
      autoInspectOpen: autoInspectOpen,
      autoInspectReload: autoInspectReload
    });
  };

  restore_options = function() {
    return chrome.storage.sync.get({
      autoInspectOpen: true,
      autoInspectReload: true
    }, function(items) {
      document.getElementById("autoInspectOpen").checked = items.autoInspectOpen;
      return document.getElementById("autoInspectReload").checked = items.autoInspectReload;
    });
  };

  $(document).ready(function() {
    restore_options();
    return $('form').on('click', 'input', function() {
      return save_options();
    });
  });

}).call(this);
