// Generated by CoffeeScript 1.6.3
var updateContextMenus,
  __hasProp = {}.hasOwnProperty;

console.log("background.js");

updateContextMenus = function(flags, port) {
  var key, onClickHandler, value, _results;
  onClickHandler = function(info, tab) {
    return port.postMessage({
      name: "contextMenuClick",
      key: info.menuItemId,
      tab: tab
    });
  };
  if (flags.length > 0) {
    _results = [];
    for (key in flags) {
      if (!__hasProp.call(flags, key)) continue;
      value = flags[key];
      _results.push(chrome.contextMenus.create({
        title: value,
        id: "" + key,
        contexts: ['all'],
        onclick: onClickHandler
      }));
    }
    return _results;
  }
};

chrome.runtime.onConnect.addListener(function(port) {
  if (port.name === "devtoolsConnect") {
    console.log(port.portId_);
    port.onMessage.addListener(function(msg) {
      return chrome.tabs.query({
        lastFocusedWindow: true,
        active: true
      }, function(tabs) {
        return chrome.tabs.sendMessage(tabs[0].id, "Give me domflags", function(response) {
          if (response) {
            return updateContextMenus(response.flags, port);
          }
        });
      });
    });
    return port.onDisconnect.addListener(function(port) {
      return chrome.contextMenus.removeAll();
    });
  }
});

chrome.tabs.onActivated.addListener(function(activeInfo) {
  return chrome.contextMenus.removeAll();
});
