// Generated by CoffeeScript 1.6.3
(function() {
  console.log("inject.js");

  console.log($('[domflag]'));

  chrome.runtime.sendMessage({
    greeting: "hello"
  }, function(response) {
    return console.log(response.farewell);
  });

}).call(this);
