// Generated by CoffeeScript 1.6.3
var port, showDomFlag;

console.log("devtools panel");

chrome.devtools.panels.elements.createSidebarPane("DOM Flags", function(sidebar) {
  return sidebar.setObject({
    some_data: "Some data to show"
  });
});

showDomFlag = function(key) {
  return chrome.devtools.inspectedWindow["eval"]("inspect($$('[domflag]')[" + key + "])");
};

chrome.devtools.network.onRequestFinished.addListener(function(request) {
  if (request) {
    return showDomFlag(0);
  }
});

showDomFlag(0);

port = chrome.runtime.connect({
  name: "devtools"
});

port.onMessage.addListener(function(msg) {
  return showDomFlag(msg.key);
});
