// Generated by CoffeeScript 1.7.1
(function() {
  var port, showDomFlag;

  showDomFlag = function(key) {
    return chrome.devtools.inspectedWindow["eval"]("inspect($$('[domflag]')[" + key + "])");
  };

  port = chrome.runtime.connect({
    name: "devtools"
  });

  port.postMessage({
    msg: "initiate"
  });

  port.onMessage.addListener(function(msg) {
    if (msg.name === "contextMenuClick" || "panelClick" || "pageReloaded" || "devtoolsOpened") {
      return showDomFlag(msg.key);
    }
  });

}).call(this);
